### ISSUE TITLE
怎么在Android中集成这个库

### ISSUE THREAD

**Issue by TonywithZhang** [hypercube1024/firefly#109]
我app包下面新建了个目录叫configs，把firefly-log.xml放进去，然后再app module的build.gradle里面implementation files("configs/firefly-log.xml")。但是运行起来报错：
create system logger exception
                                                                                                    javassist.NotFoundException: com.fireflysource.common.slf4j.LazyLogger
                                                                                                    	at javassist.ClassPool.get(ClassPool.java:430)
                                                                                                    	at com.fireflysource.common.bytecode.JavassistClassProxyFactory.buildClass(JavassistClassProxyFactory.java:153)
                                                                                                    	at com.fireflysource.common.bytecode.JavassistClassProxyFactory.createProxy(JavassistClassProxyFactory.java:34)
                                                                                                    	at com.fireflysource.common.sys.SystemLogger.create(SystemLogger.java:27)
                                                                                                    	at com.fireflysource.net.tcp.aio.AioTcpChannelGroup.<clinit>(AioTcpChannelGroup.kt:20)
                                                                                                    	at com.fireflysource.net.CommonTcpChannelGroup.<clinit>(CommonTcpChannelGroup.kt:22)
                                                                                                    	at com.fireflysource.$.tcpClient($.java:152)
                                                                                                    	at com.example.remotemanager.viewModels.pages.WifiViewModel$handleIntents$1$1$emit$2.invokeSuspend(WifiViewModel.kt:71)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-05-05 15:23:15.672 11211-11349 AndroidRuntime          com.example.remotemanager            E  FATAL EXCEPTION: DefaultDispatcher-worker-1
                                                                                                    Process: com.example.remotemanager, PID: 11211
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.fireflysource.net.CommonTcpChannelGroup.<clinit>(CommonTcpChannelGroup.kt:22)
                                                                                                    	at com.fireflysource.$.tcpClient($.java:152)
                                                                                                    	at com.example.remotemanager.viewModels.pages.WifiViewModel$handleIntents$1$1$emit$2.invokeSuspend(WifiViewModel.kt:71)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@67267c5, Dispatchers.IO]
                                                                                                    Caused by: java.lang.IllegalStateException: javassist.NotFoundException: com.fireflysource.common.slf4j.LazyLogger
                                                                                                    	at com.fireflysource.common.sys.SystemLogger.create(SystemLogger.java:34)
                                                                                                    	at com.fireflysource.net.tcp.aio.AioTcpChannelGroup.<clinit>(AioTcpChannelGroup.kt:20)
                                                                                                    	... 11 more
                                                                                                    Caused by: javassist.NotFoundException: com.fireflysource.common.slf4j.LazyLogger
                                                                                                    	at javassist.ClassPool.get(ClassPool.java:430)
                                                                                                    	at com.fireflysource.common.bytecode.JavassistClassProxyFactory.buildClass(JavassistClassProxyFactory.java:153)
                                                                                                    	at com.fireflysource.common.bytecode.JavassistClassProxyFactory.createProxy(JavassistClassProxyFactory.java:34)
                                                                                                    	at com.fireflysource.common.sys.SystemLogger.create(SystemLogger.java:27)
                                                                                                    	... 12 more

**Comment by kevin0016** [comment]
自动回复：您好，我是梁学凯，信已收到，
