### ISSUE TITLE
template file parse error

### ISSUE THREAD

**Issue by 1131245970** [hypercube1024/firefly#27]
...\page\template\_compiled_view\_bidding_pandect.java:10: 错误: 代码过长
	public _bidding_pandect(TemplateFactory templateFactory){this.templateFactory = templateFactory;}
	       ^
...\page\template\_compiled_view\_bidding_pandect.java:8: 错误: 常量过多
public class _bidding_pandect extends AbstractView {
       ^
2 个错误 
com.firefly.template.exception.TemplateFileReadException: template file parse error
	at com.firefly.template.parser.ViewFileReader.<init>(ViewFileReader.java:27)
	at com.firefly.template.TemplateFactory.init(TemplateFactory.java:53)
	at com.firefly.mvc.web.view.TemplateView.init(TemplateView.java:32)
	at com.firefly.server.ServerAnnotationWebContext.viewInit(ServerAnnotationWebContext.java:41)
	at com.firefly.server.ServerAnnotationWebContext.<init>(ServerAnnotationWebContext.java:32)
	at com.firefly.server.ServerBootstrap.start(ServerBootstrap.java:38)
......

**Comment by hypercube1024** [comment]
很早以前的版本了，后面优化过这个问题。最新的版本已经使用mustache模板引擎替换原有的
